\documentclass{bioinfo}
\copyrightyear{2018} \pubyear{2018}

\access{Advance Access Publication Date: Day Month Year}
\appnotes{Manuscript Category}

\usepackage{natbib}

\begin{document}
\firstpage{1}

\title[BiocPkgTools: Inspecting the Bioconductor ecosystem]{BiocPkgTools: Utilities for inspecting the Bioconductor package ecosystem}
\author[Davis \textit{et~al}.]{Martin T. Morgan\,$^{\text{\sfb 2}}$, Lori Shepherd\,$^{\text{\sfb 2}}$, Vincent J. Carey\,$^{\text{\sfb 3}}$, and Sean Davis\,$^{\text{\sfb 1,}*}$}
\address{$^{\text{\sf 1}}$Center for Cancer Research, National Cancer Institute, National Institutes of Health, Bethesda, MD 20892, USA\\
  $^{\text{\sf 2}}$Roswell Park Comprehensive Cancer Center, Buffalo, NY 14203, USA\\
  $^{\text{\sf 3}}$Channing Division of Network Medicine, Brigham and Women's Hospital, Boston, MA 02115, USA}

\corresp{$^\ast$To whom correspondence should be addressed.}

\history{Received on XXXXX; revised on XXXXX; accepted on XXXXX}

\editor{Associate Editor: XXXXXXX}

\abstract{\textbf{Motivation:} The Bioconductor project, a large
  collection of open source software for the comprehension of
  large-scale biologic data, continues to grow with the contribution
  of new packages added each week.  The motivation for the
  BiocPkgTools software is to allow developers and the Bioconductor
  community to easily access the Bioconductor package ecosystem and
  associated metadata, leading to applications such as custom
  reporting, data and text mining of Bioconductor packages, graph
  analytics over package dependencies, and advanced, custom search
  approaches. \\ \textbf{Results:} The BiocPkgTools package has been
  incorporated into the Bioconductor project, installs using standard
  procedures, and runs on any system supporting R. It provides easy
  access to detailed package metadata, longitudinal package download
  statistics, package dependencies, and build reports, all as tidy
  data. BiocPkgTools can convert from tidy data structures to graph
  structures, enabling graph-based analytics and visualization. Full
  documentation and example use cases are
  included. \\ \textbf{Availability:} The BiocPkgTools software and
  complete documentation are available from Bioconductor
  (\href{https://Bioconductor.org/packages/BiocPkgTools}{https://Bioconductor.org/packages/BiocPkgTools})
  and from Github
  (\href{https://github.com/seandavi/BiocPkgTools}{https://github.com/seandavi/BiocPkgTools}).\\ \textbf{Contact:}
  \href{seandavi@gmail.com}{seandavi@gmail.com}}

\maketitle

<<init, include=FALSE>>=
library(knitr)
opts_chunk$set(cache=as.logical(Sys.getenv('NOCACHE', TRUE)),
               size="small")
options(width=40)
@ 

<<loadData, include=FALSE>>=
library(magrittr)
library(dplyr)
library(BiocPkgTools)
pkgdata = biocPkgList()
dldata = biocDownloadStats() 
@ 

\section{Introduction}

Bioconductor is a open source software project (comprising
\Sexpr{nrow(pkgdata)} individual packages) and community devoted to
the analysis and comprehension of large-scale biologic data. The
project maintains an automated system that ensures that packages in
the Bioconductor project build successfully and pass basic
checks. Package downloads are tracked and aggregated by package and
month, longitudinally. Finally, package details such as title,
description, version, author, and dependencies on other R packages are
compiled based on package metadata. The current size and growth of the
project suggests that there may be merit in facilitating data science
approaches to the contents of the Bioconductor ecosystem. Therefore,
we have developed a small suite of tools to provide easy access to
project data such download statistics, bulk package metadata, and
package build status. Developers, project leaders, open source
software researchers, and Bioconductor end users can build on the
availability of these data for applications such as custom reporting,
dependency graph analytics, package filtering, and text mining.

\section{Implementation}

BiocPkgTools is implemented as a standard R package and hosted in the
Bioconductor repository. All functions are documented and include
examples. An included vignette (tutorial) demonstrates features and
capabilities.

\section{Features and usage}

BiocPkgTools core functionality is to expose Bioconductor project and
package metadata as tidy \citep{Wickham2014-ye} objects. Package
metadata, monthly summaries of download statistics, and build reports
from the Bioconductor automated build process. 

<<downloads>>=
library(BiocPkgTools)
dlstats = biocDownloadStats()
head(dlstats, 3)
@ 

<<buildreport>>=
buildrep = biocBuildReport()
tail(buildrep,3)
@ 

Take a look at Figure \ref{fig:dependencygraph}.


\begin{figure}
  \includegraphics[width=\linewidth]{BiocPkgToolsDependencyGraph}
  \caption{Visualizing dependencies between all packages within one
    degree of the GEOquery package using the visNetwork package
    \citep{visNetwork}. Links are colored based on type (Suggests,
    Depends, and Imports) and arrows point to the ``dependent''
    package. }
  \label{fig:dependencygraph}
\end{figure}

\section{Conclusion}

\section*{Acknowledgements}



\section*{Funding}

Research reported in this publication was supported by the National Human Genome Research Institute of the National Institutes of Health under award number U41HG004059, the National Cancer Institute of the National Institutes of Health under award number U24CA180996, and the Center for Cancer Research, part of the Intramural Research Program at the National Cancer Institute at the National Institutes of Health. Part of this work was performed on behalf of the SOUND Consortium and funded under the EU H2020 Personalizing Health and Care Program, Action contract number 633974.

\bibliographystyle{natbib}
%\bibliographystyle{achemnat}
%\bibliographystyle{plainnat}
%\bibliographystyle{abbrv}
%\bibliographystyle{bioinformatics}
%
%\bibliographystyle{plain}
%
\bibliography{references}

\end{document}
