\documentclass[9pt,a4paper]{extarticle}
\usepackage{f1000_styles}
\usepackage{hyperref}
\usepackage{todonotes}

\usepackage{tabularx}

%% Default: numerical citations
\usepackage[numbers]{natbib}

%% Uncomment this lines for superscript citations instead
% \usepackage[super]{natbib}

%% Uncomment these lines for author-year citations instead
% \usepackage[round]{natbib}
% \let\cite\citep



%% \title[BiocPkgTools: Inspecting the Bioconductor ecosystem]{BiocPkgTools: Utilities for inspecting the Bioconductor package ecosystem}
%% \author[Davis \textit{et~al}.]{Martin T. Morgan\,$^{\text{\sfb 2}}$, Lori Shepherd\,$^{\text{\sfb 2}}$, Vincent J. Carey\,$^{\text{\sfb 3}}$, and Sean Davis\,$^{\text{\sfb 1,}*}$}
%% \address{$^{\text{\sf 1}}$Center for Cancer Research, National Cancer Institute, National Institutes of Health, Bethesda, MD 20892, USA\\
%%   $^{\text{\sf 2}}$Roswell Park Comprehensive Cancer Center, Buffalo, NY 14203, USA\\
%%   $^{\text{\sf 3}}$Channing Division of Network Medicine, Brigham and Women's Hospital, Boston, MA 02115, USA}

%% \corresp{$^\ast$To whom correspondence should be addressed.}


\begin{document}

\pagestyle{front}

\title{\textit{BiocPkgTools}: Toolkit for Mining the \emph{Bioconductor} Package Ecosystem}

\author[1]{Shian Su}
\author[2]{Vincent~J. Carey}
\author[3]{Lori Shepherd}
\author[1]{Matthew Ritchie}
\author[3]{Martin~T. Morgan}
\author[4]{Sean Davis}
\affil[1]{Molecular Medicine Division, The Walter and Eliza Hall Institute of Medical Research, Parkville, Australia}
\affil[2]{Channing Division of Network Medicine, Brigham and Women's Hospital, Boston, MA, USA}
\affil[3]{Roswell Park Comprehensive Cancer Center, Buffalo, NY, USA}
\affil[4]{Center for Cancer Research, National Cancer Institute, National Institutes of Health, Bethesda, MD, USA}

\maketitle
\thispagestyle{front}


\begin{abstract}
  \\ \textbf{Motivation:} The \emph{Bioconductor} project, a large collection of
  open source software for the comprehension of large-scale biological
  data, continues to grow with new packages added each week,
  motivating the development of software tools focused on exposing
  package metadata to developers and users. The resulting BiocPkgTools
  package facilitates access to the \emph{Bioconductor} package ecosystem and
  associated metadata in computable form, enabling potential
  downstream applications such as custom reporting, data and text
  mining of \emph{Bioconductor} packages, graph analytics over package
  dependencies, and advanced, custom search approaches. \\
  \textbf{Results:} The BiocPkgTools package has been incorporated
  into the \emph{Bioconductor} project, installs using standard procedures,
  and runs on any system supporting R. It provides functions to load
  detailed package metadata, longitudinal package download statistics,
  package dependencies, and \emph{Bioconductor} build reports, all in ``tidy
  data'' form. BiocPkgTools can convert from tidy data structures to
  graph structures, enabling graph-based analytics and
  visualization. An end-user-friendly graphical package explorer aids
  in task-centric package discovery. Full documentation and example
  use cases are included. \\ \textbf{Availability:} The BiocPkgTools
  software and complete documentation are available from \emph{Bioconductor}
  (\href{https://bioconductor.org/packages/BiocPkgTools}{https://bioconductor.org/packages/BiocPkgTools}).
\end{abstract}

\section*{Keywords}

Bioconductor, data mining, R, open data, software, data science, software development, bioinformatics


<<init, include=FALSE>>=
library(knitr)
opts_chunk$set(cache=as.logical(Sys.getenv('NOCACHE', TRUE)),
               size="small")
options(width=70)
@ 

<<loadData, include=FALSE>>=
library(magrittr)
library(dplyr)
library(BiocPkgTools)
pkgdata = biocPkgList()
dldata = biocDownloadStats() 
@ 

\clearpage
\pagestyle{main}

\section*{Introduction}

\emph{Bioconductor} is a open source software project (comprising
\Sexpr{nrow(pkgdata)} individual software packages) and community for
the analysis and comprehension of large-scale biological data. The
project maintains an automated system that ensures that packages in
the \emph{Bioconductor} project build successfully and pass basic
checks. Package downloads are tracked and aggregated by package and
month, longitudinally. Finally, package details such as title,
description, version, author, and dependencies on other R packages are
compiled based on package metadata.

The current size and growth of the \emph{Bioconductor} project suggests that
there is merit in exposing computable forms of the metadata describing
the \emph{Bioconductor} package ecosystem. To that end, we developed a small
suite of tools to provide easy access to project details such as download
statistics, bulk package metadata, and package build
status. Developers, project leaders, open source software researchers,
and \emph{Bioconductor} end users can build on the availability of these data
for applications such as custom reporting, dependency graph analytics,
package filtering, and text mining.


\section*{Features and usage}

The core functionality of BiocPkgTools is to expose
\emph{Bioconductor} project and package metadata as tidy
\citep{Wickham2014-ye} objects. The data presented by the package are
accessed directly from online resources available from
\emph{Bioconductor}. As such, the package relies on web connectivity and
uses the most recent data. Installation instructions are detailed
on the package website.

Package functionality can be roughly divided into data access, data presentation, and graph/network functionality. See Table \ref{tab:functions} for an overview.

\begin{table}[h]
  \caption{Main package functions and descriptions.}
  \label{tab:functions}
  \begin{tabularx}{\linewidth}{ l X }
    \hline 
    Name & Functionality \\
    \hline 
    biocPkgList & Package details including description, author and maintainer, dependencies, URLs, bug report mechanism \\
    biocDownloadStats & Monthly download statistics for all packages \\
    biocbuildReport & \emph{Bioconductor} build report for all packages and systems \\
    biocExplore & Interactive, browsable ``bubble plot'' of \emph{Bioconductor} packages and details \\
    problemPage & Interactive, customized build report for an individual package author \\
    buildPkgDependencyDataFrame & Package dependencies as data frame (tibble) \\
    buildPkgDependencyIgraph & Package dependencies as a graph \\
    inducedSubgraphByPkgs & Create a minimal subgraph of \emph{Bioconductor} dependencies based on specific packages \\
    subgraphByDegree & Create a subgraph of all packages within a given degree of a single package \\
    \hline
  \end{tabularx} 
\end{table}

After installing BiocPkgTools, the \texttt{biocDownloadStats} function
can generate a tidy data structure summarizing monthly download
statistics (both total and unique IP addresses) for all \emph{Bioconductor}
packages.

<<downloads>>=
library(BiocPkgTools)
dlstats = biocDownloadStats()
head(dlstats, 3)
@ 

The \texttt{biocBuildReport} function gathers information from the
\emph{Bioconductor}
\href{http://bioconductor.org/checkResults/release/bioc-LATEST/}{build
  report site} and can be used, for example, to summarize the ``build
status'' for all \emph{Bioconductor} pacakages.

<<buildreport>>=
buildrep = biocBuildReport(version = "3.8")
table(buildrep$stage, buildrep$result)
@

These data are useful to developers to track the health of their
software either programmatically or via a searchable, sortable table
from the \texttt{problemPage} function.

As an alternative to google and the \emph{Bioconductor} online software list, the \texttt{biocExplore} function offers interactive and graphical approach to package browsing (see Figure \ref{fig:biocexplore}). 

\begin{figure}
  \includegraphics[width=\linewidth]{biocExplore}
  \caption{The \texttt{biocExplore} function opens an interactive web application that allows users to select focused groups of \emph{Bioconductor} packages to view as a bubble plot. Bubbles are sized based on download statistics. Hovering over a bubble will give download number while clicking on a bubble will pop up a package details page, including a link to the package landing page.}
  \label{fig:biocexplore}
\end{figure}

The \emph{Bioconductor} package ecosystem is, by design, highly
interconnected via package dependencies. Several functions in the
BiocPkgTools package provide examples of package dependency graph
creation and visualization. Figure \ref{fig:dependencygraph} displays
packages within one degree of dependency relationship of the GEOquery
package.

\begin{figure}
  \includegraphics[width=\linewidth]{BiocPkgToolsDependencyGraph}
  \caption{The \texttt{subgraphByDegree} function builds a data
    visualization of dependencies between all packages within one
    degree of the GEOquery package using the visNetwork package
    \citep{visNetwork}. Links are colored based on type (Suggests,
    Depends, and Imports) and arrows point to the ``dependent''
    package. }
  \label{fig:dependencygraph}
\end{figure}

\section*{Implementation}

BiocPkgTools is implemented as a standard R package and hosted in the
\emph{Bioconductor} repository. All functions are documented and include
examples. An included tutorial (vignette) demonstrates features and
capabilities. 

\section*{Data availability} % Optional - only if novel data or analyses are included
All data accessed and used by the BiocPkgTools package are publicly available and are updated regularly at the \emph{Bioconductor} project. 

\section*{Software availability}
This section will be generated by the Editorial Office before publication. Authors are asked to provide some initial information to assist the Editorial Office, as detailed below.
\begin{itemize}
\item Software URL: \href{https://bioconductor.org/packages/BiocPkgTools}{https://bioconductorg.org/packages/BiocPkgTools} 
\item Version Control URL: \href{https://github.com/seandavi/BiocPkgTools}{https://github.com/seandavi/BiocPkgTools} 
\item Software package DOI: \href{https://doi.org/doi:10.18129/B9.bioc.BiocPkgTools}{doi:10.18129/B9.bioc.BiocPkgTools}
\item Software License: MIT License
\end{itemize}



\section*{Author contributions}
SD conceived of the project. All authors have reviewed and edited the manuscript. Authors contributing to code include MM, SD, SS, LS, and VC. 


\section*{Competing interests}
No competing interests were disclosed.
\todo{Please add any competing interests.}

\section*{Grant information}

Research reported in this publication was supported by the National
Human Genome Research Institute of the National Institutes of Health
under award number U41HG004059, the National Cancer Institute of the
National Institutes of Health under award number U24CA180996, and the
Center for Cancer Research, part of the Intramural Research Program at
the National Cancer Institute at the National Institutes of
Health. Part of this work was performed on behalf of the SOUND
Consortium and funded under the EU H2020 Personalizing Health and Care
Program, Action contract number 633974.
\todo{Please add any other grant/support information as needed.}


\bibliographystyle{natbib}
%\bibliographystyle{achemnat}
%\bibliographystyle{plainnat}
%\bibliographystyle{abbrv}
%\bibliographystyle{bioinformatics}
%
%\bibliographystyle{plain}
%
\bibliography{references}

\end{document}
